### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by exxosuk** [rmcgirr83/elonw#17]
I am using phpbb 3.3.3 with board rules 2.1.2.  The rules page seems to work fine, but I get errors when the extension is enabled... With the extension off, I don't get the errors. 

![Capture](https://user-images.githubusercontent.com/22227683/108770965-e1250580-7552-11eb-80c7-41cdfaf40cdd.PNG)

**Comment by rmcgirr83** [comment]
What version of this extension are you using and what do you have for the html in the board rules extension.

**Comment by exxosuk** [comment]
version 2.1.2

The same html in the rules is installed on my live forum (albeit older versions of stuff)  https://www.exxoshost.co.uk/forum/app.php/rules

**Comment by rmcgirr83** [comment]
Uhmmm, there is no version 2.1.2 of this extension.  However, your js error is most likely due to this type of code
`<a class="rule-anchor postlink" href="#rule-1a">#</a>` it is the href that is the issue.

**Comment by rmcgirr83** [comment]
Try change this code in the js of the extension

`	var IgnoreClasses = [
		'posterip',
		'share-button',
		'fancybox',
		'lightbox',
		'colorbox'
	];`
To this

`	var IgnoreClasses = [
		'posterip',
		'share-button',
		'fancybox',
		'lightbox',
		'colorbox',
		'rule-item'
	];`
	
You'll have to disable the extension first, make the change, then re-enable.  May even have to hard refresh your browser.

**Comment by exxosuk** [comment]
Hold on bare with me, I am really confused on whos extensions whos at the moment..  I seem to have board rules by someone totally different somehow.

**Comment by exxosuk** [comment]
On my old forum it says this...

![1](https://user-images.githubusercontent.com/22227683/108778163-e25b3000-755c-11eb-957a-fed560f3e391.PNG)

But when I download from your git hub.. it says this..

![2](https://user-images.githubusercontent.com/22227683/108778191-ec7d2e80-755c-11eb-9ebb-8c6b0e44886a.PNG)

**Comment by exxosuk** [comment]
I think ive confused your extensions with someone elses sorry :(

**Comment by rmcgirr83** [comment]
You're using 1.0.6 of this extension, latest is 1.0.10. Try that version. (per the first pic you posted)

The Board Rules version you are using is 2.1.2 (per the second pic you posted).

**Comment by exxosuk** [comment]
Sorry ive mixed you up with another developer.. I am using 2 of your extensions (great btw!) but I dont have any problems with "stop forum spam" or "open links in new windows"   it was the board rules I thought you did as well....

![Capture](https://user-images.githubusercontent.com/22227683/108779063-3fa3b100-755e-11eb-8c69-5893f69c9ba6.PNG)

**Comment by exxosuk** [comment]
Tried to buy you a beer, but takes me to paypal login and I am banned from paypal :(
