### ISSUE TITLE
Hide 'Open in new Window' Icon

### ISSUE THREAD

**Issue by SteseDav** [rmcgirr83/elonw#18]
Is there a way to hide/remove the 'Opens in new window' icon on links?

**Comment by rmcgirr83** [comment]
On this line https://github.com/rmcgirr83/elonw/blob/master/styles/all/template/js/elonw.js#L33

remove this `.addClass("elonw")`

**Comment by rmcgirr83** [comment]
That is correct. You may have to refresh your browser to reload the js after making that change.
